FROM quay.io/jupyter/scipy-notebook
LABEL org.opencontainers.image.authors="rosatrancoso@gmail.com"

ADD requirements_gis.yml /tmp/requirements_gis.yml
RUN mamba env update --name base --file /tmp/requirements_gis.yml
