FROM quay.io/jupyter/scipy-notebook
LABEL org.opencontainers.image.authors="rosatrancoso@gmail.com"

ADD requirements.yml /tmp/requirements.yml
RUN mamba env update --name base --file /tmp/requirements.yml
